# Generated by Django 5.0.6 on 2024-05-09 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=350)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(max_length=255, verbose_name='تام خانوادگی')),
                ('age', models.PositiveSmallIntegerField(verbose_name='سن')),
                ('job', models.CharField(max_length=255, null=True, verbose_name='شغل')),
                ('work_experience', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='سابقه شغلی')),
                ('education', models.CharField(choices=[('hs', 'تحصیلات دبیرستان'), ('di', 'دیپلم'), ('bd', 'کارشناسی'), ('ad', 'کارشناسی ارشد'), ('dc', 'دکتری و بالاتر')], max_length=2, null=True, verbose_name='تحصیلات')),
                ('marital_status', models.CharField(choices=[('ma', 'متعهد'), ('si', 'مجرد'), ('di', 'مطلفه')], max_length=2, null=True, verbose_name='وضعیت تعهد')),
                ('height', models.PositiveSmallIntegerField(verbose_name='قد (به سانتی متر)')),
                ('weight', models.FloatField(verbose_name='وزن (به متر)')),
                ('bmi', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=150)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdq.question')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdq.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdq.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdq.user')),
            ],
        ),
    ]
