# Generated by Django 5.0.6 on 2024-05-14 10:48

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'انتخاب', 'verbose_name_plural': 'انتخاب ها'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'رای', 'verbose_name_plural': 'رای ها'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=150, verbose_name='متن گزینه ها'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdq.question', verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10, message='حداقل سن 10 سال است'), django.core.validators.MaxValueValidator(150, message='سن بیشتر از 150 سال قابل قبول نیست')], verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(110, message='حداقل قد 110 سانتی متر است'), django.core.validators.MaxValueValidator(250, message='قد وارد شده بیشتر از مقدار معقول است')], verbose_name='قد (به سانتی متر)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, choices=[('off', 'اداری'), ('eng', 'فنی'), ('pro', 'تولید'), ('ser', 'خدمات')], max_length=3, null=True, verbose_name='رسته شغلی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(choices=[('ma', 'متعهد'), ('si', 'مجرد'), ('di', 'مطلقه')], max_length=2, null=True, verbose_name='وضعیت تعهد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(20, message='وزن مورد نظر کمتر از مقدار معقول است'), django.core.validators.MaxValueValidator(250, message='وزن وارد شده بیشتر از مقدار محدود شده است')], verbose_name='وزن (به متر)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_experience',
            field=models.PositiveSmallIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(60, message='حداکثر سابقه شغلی 60 سال است')], verbose_name='سابقه شغلی'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdq.choice', verbose_name='انتخاب'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdq.question', verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdq.user', verbose_name='کاربر'),
        ),
    ]
