# Generated by Django 4.2.13 on 2024-05-22 21:14

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=150, verbose_name='متن گزینه ها')),
            ],
            options={
                'verbose_name': 'انتخاب',
                'verbose_name_plural': 'انتخاب ها',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=255, verbose_name='عنوان سوال')),
                ('question_text', models.CharField(max_length=350, verbose_name='متن سوال')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10, message='حداقل سن 10 سال است'), django.core.validators.MaxValueValidator(150, message='سن بیشتر از 150 سال قابل قبول نیست')], verbose_name='سن')),
                ('job_category', models.CharField(choices=[('off', 'اداری'), ('eng', 'فنی'), ('pro', 'تولید'), ('ser', 'خدمات')], max_length=3, verbose_name='رسته شغلی')),
                ('job', models.CharField(max_length=255, verbose_name='شغل')),
                ('organ', models.CharField(max_length=255, verbose_name='نام سازمان')),
                ('work_experience', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60, message='حداکثر سابقه شغلی 60 سال است')], verbose_name='سابقه شغلی')),
                ('education', models.CharField(choices=[('hs', 'تحصیلات دبیرستان'), ('di', 'دیپلم'), ('bd', 'کارشناسی'), ('ad', 'کارشناسی ارشد'), ('dc', 'دکتری و بالاتر')], max_length=2, verbose_name='تحصیلات')),
                ('marital_status', models.CharField(choices=[('ma', 'متعهد'), ('si', 'مجرد'), ('di', 'مطلقه')], max_length=2, verbose_name='وضعیت تعهد')),
                ('height', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(110, message='حداقل قد 110 سانتی متر است'), django.core.validators.MaxValueValidator(250, message='قد وارد شده بیشتر از مقدار معقول است')], verbose_name='قد (به سانتی متر)')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(20, message='وزن مورد نظر کمتر از مقدار معقول است'), django.core.validators.MaxValueValidator(250, message='وزن وارد شده بیشتر از مقدار محدود شده است')], verbose_name='وزن (به کیلوگرم)')),
                ('bmi', models.FloatField(blank=True, null=True, verbose_name='BMI')),
                ('comment', models.CharField(blank=True, max_length=755, null=True, verbose_name='نظرات و پیشنهادات')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ رای')),
                ('box', models.CharField(blank=True, max_length=2, null=True, verbose_name='تعداد ساعت کار')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.choice', verbose_name='انتخاب')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.question', verbose_name='سوال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.user', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رای',
                'verbose_name_plural': 'رای ها',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.question', verbose_name='سوال'),
        ),
    ]
