# Generated by Django 4.2.13 on 2024-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_rename_user_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(choices=[('0', 'هرگز'), ('1', 'به ندرت'), ('2', 'بعضی اوقات'), ('3', 'اغلب'), ('4', 'تقریبا همیشه')], max_length=1, verbose_name='متن گزینه ها'),
        ),
    ]
