# Generated by Django 4.2.13 on 2024-06-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_vote_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='box',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد ساعت کار'),
        ),
    ]
