# Generated by Django 4.2.13 on 2024-06-01 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_alter_vote_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 22, 29, 29, 465966)),
        ),
    ]
