# Generated by Django 4.2.13 on 2024-06-03 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_usermodel_date_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 21, 43, 7, 197959)),
        ),
    ]
