# Generated by Django 4.2.13 on 2024-06-05 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_choice_2_question_2_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 12, 6, 19, 723042)),
        ),
    ]
