# Generated by Django 4.2.13 on 2024-06-05 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0010_choice_3_question_3_alter_usermodel_date_join_vote_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 12, 17, 39, 22902)),
        ),
    ]
