# Generated by Django 4.2.13 on 2024-06-05 08:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0011_alter_usermodel_date_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 12, 23, 59, 357872)),
        ),
        migrations.AlterField(
            model_name='vote_3',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poll.choice_3', verbose_name='انتخاب'),
        ),
    ]
