# Generated by Django 4.2.13 on 2024-06-05 08:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0012_alter_usermodel_date_join_alter_vote_3_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_3',
            name='question_related',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='related_question', to='poll.question_2', verbose_name='سوال مربوط'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 12, 26, 41, 992084)),
        ),
    ]
