# Generated by Django 4.2.13 on 2024-06-06 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0013_question_3_question_related_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_2',
            name='question_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 23, 5, 20, 211829)),
        ),
    ]
