# Generated by Django 4.2.13 on 2024-06-10 19:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0014_question_2_question_img_alter_usermodel_date_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(choices=[('man', 'مرد'), ('wom', 'زن'), ('otw', 'سایر')], default='man', max_length=3, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 22, 33, 2, 548253)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='marital_status',
            field=models.CharField(choices=[('ma', 'متعهد'), ('si', 'مجرد'), ('di', 'مطلقه')], max_length=2, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='work_experience',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(60, message='حداکثر سابقه شغلی 60 سال است')], verbose_name='سابقه شغلی'),
        ),
    ]
