# Generated by Django 4.2.13 on 2025-02-02 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0015_usermodel_gender_alter_usermodel_date_join_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نظرات و پیشنهادات'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 2, 23, 13, 4, 587589)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(choices=[('man', 'مرد'), ('wom', 'زن'), ('otw', 'سایر')], max_length=3, verbose_name='جنسیت'),
        ),
    ]
